<a href="https://colab.research.google.com/github/IagoAlfiro/Exerc1Aula/blob/master/(IagoAlbuquerque)semana11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

wines = pd.read_csv("https://raw.githubusercontent.com/simonneutert/wine_quality_data/master/winequality-red.csv", sep=';')
wines

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [15]:
wines.describe()

       fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [16]:
wines[wines['pH']>=3]

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1570 rows x 12 columns]

In [17]:
wines.head(10)

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5
6            7.9              0.60         0.06  ...       0.46      9.4        5
7            7.3              0.65         0.00  ...       0.47     10.0        7
8            7.8              0.58         0.02  ...       0.57      9.5        7
9            7.5              0.50         0.36  ...       0.80     10.5        5

[10 rows x 12 columns]

In [23]:
BomVinho = wines[wines['quality'] >= 6]
BomVinho

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
3              11.2              0.28         0.56  ...       0.58      9.8        6
7               7.3              0.65         0.00  ...       0.47     10.0        7
8               7.8              0.58         0.02  ...       0.57      9.5        7
16              8.5              0.28         0.56  ...       0.75     10.5        7
19              7.9              0.32         0.51  ...       1.08      9.2        6
...             ...               ...          ...  ...        ...      ...      ...
1592            6.3              0.51         0.13  ...       0.75     11.0        6
1593            6.8              0.62         0.08  ...       0.82      9.5        6
1595            5.9              0.55         0.10  ...       0.76     11.2        6
1596            6.3              0.51         0.13  ...       0.75     11.0        6
1598            6.0              0.31         0.47  ...       0.66     11.0        6

[855 rows x 12 columns]

IagoAlbuquerque
0050015542
O dataset utilizado pode ser utilizado para determinar quais fatores  determinam a qualidade de um vinho vermelho.